
---
deployment:
  tasks:
    # ==== config (adjust these!) ====
    - export NPM="/opt/cpanel/ea-nodejs20/bin/npm"         # change to ea-nodejs18 if your server uses Node 18
    - export APP_ROOT="$(pwd)"
    - export BUILD_DIR="$APP_ROOT/dist"
    - export DEPLOYPATH="/home1/aaswxfeb/creativeenergy.pk"       # <-- change USERNAME & path (e.g., /home/USERNAME/subdomains/app)

    # ==== build ====
    - $NPM ci                                              # or `install` if you don't use a lockfile
    - $NPM run build                                       # produces ./dist

    # ==== deploy ====
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/rsync -a --delete "$BUILD_DIR/" "$DEPLOYPATH/"

    # optional: stamp the deployment
    - /bin/date -u +"%Y-%m-%dT%H:%M:%SZ" > "$DEPLOYPATH/.last_deploy_utc"
