---
deployment:
  tasks:
    # --- config ---
    - export NODE="/opt/cpanel/ea-nodejs20/bin/node"
    - export NPM="/opt/cpanel/ea-nodejs20/bin/npm"
    - export REPO_ROOT="$(pwd)"
    - export DEPLOYPATH="/home1/aaswxfeb/creativeenergy.pk/app"   # e.g. /home/USERNAME/domains/sub.example.com/public_html

    # --- build ---
    - $NPM ci
    - $NPM run build

    # --- deploy ---
    # create deploy dir if missing
    - /bin/mkdir -p "$DEPLOYPATH"
    # sync built files (deletes removed files on server)
    - /bin/rsync -a --delete "$REPO_ROOT/dist/" "$DEPLOYPATH/"

    # --- optional: keep a simple release marker ---
    - /bin/date -u +"%Y-%m-%dT%H:%M:%SZ" > "$DEPLOYPATH/.last_deploy_utc"
